version: '3'

services:

    app:
        container_name: assets-api-dev
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/app/
            - /app/node_modules
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
            PORT: ${PORT}            
            CLIENT_DOMAIN: ${CLIENT_DOMAIN}   
            JWT_SECRET: ${JWT_SECRET}    

    db:
        container_name: assets-db-dev
        image: nachodocker1714/assets-db:${DB_VERSION}
        restart: always
        ports:
            - ${PORT_DB}:${PORT_DB}
        volumes:
            - postgres-db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}    
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}            
            POSTGRES_DB: ${POSTGRES_DB}  

volumes:
    postgres-db:
        external: false